name: Build/release

on:
  create:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      GITHUB_TOKEN: ${{ secrets.github_token }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_IDENTITY: ${{ secrets.APPLE_IDENTITY }}
      APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Add MacOS certs
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: chmod +x scripts/add-osx-cert.sh && ./scripts/add-osx-cert.sh
        env:
          APPLE_CERT: ${{ secrets.APPLE_CERT }}
          APPLE_CERT_PASSWORD: ${{ secrets.APPLE_CERT_PASSWORD }}

      - name: Install
        run: yarn

      - name: publish
        run: yarn run publish